### ISSUE TITLE
Progress bar is not responsive

### ISSUE THREAD

**Issue by jooola** [heyarne/airsonic-ui#39]
This is only a minor issue. Still the progress bar don't shrink after changing the windows size.

**Comment by heyarne** [comment]
I also see this is a minor issue. People changing browser window sizes are usually developers testing for responsiveness. :) It would still be nice to have though, e.g. when changing the screen orientation.

**Comment by jooola** [comment]
When splitting screen in 2, and resizing windows on half screen seems to be a common use case. Anyway yeah I did wanted to test responsiveness :wink:
